# Generated by Django 5.2.15 on 2026-06-26 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_prefix', models.CharField(db_index=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='easy_agent_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email', 'name'],
                'indexes': [models.Index(fields=['token_prefix', 'is_active'], name='boards_agen_token_p_4c3a93_idx'), models.Index(fields=['user', 'is_active'], name='boards_agen_user_id_a9da69_idx')],
            },
        ),
    ]
