# Generated by Django 5.2.15 on 2026-06-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_agenttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttoken',
            name='scope',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write')], default='read', max_length=20),
        ),
    ]
